- name: create virtualenv
  shell:
    cmd: "~/.pyenv/versions/{{ python_version }}/bin/python -m venv {{ virtualenv }}"
- name: install python packages
  environment:
    PATH: "{{ exec_path|default(omit) }}"
  pip:
    requirements: "{{ requirements_file }}"
    virtualenv: "{{ virtualenv }}"
  notify:
    - restart application
