- name: create virtualenv
  shell:
    cmd: "{{ python }} -m venv {{ virtualenv }} --prompt {{ project_name }}"
- name: install python packages
  environment:
    PATH: "{{ exec_path|default(omit) }}"
  pip:
    requirements: "{{ requirements_file }}"
    virtualenv: "{{ virtualenv }}"
  notify:
    - restart application
