- name: install python packages
  environment:
    PATH: "{{ exec_path|default(omit) }}"
  pip:
    requirements: "{{ requirements_file }}"
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "{{ python }} -m venv --prompt {{ project_name }}"
  notify:
    - restart application
