- name: clone/pull project repository
  git:
    repo={{ project_repo }}
    dest={{ deploy_dir }}
    accept_hostkey=yes
    version={{ project_version }}
    key_file={{ git_key_file if git_key_file is defined else None }}
