- name: create nginx config
  become: yes
  template:
    src: "{{ nginx_template }}"
    dest: "/etc/nginx/sites-available/{{ service_name }}"
  notify:
  - restart nginx

- name: symlink nginx config
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ service_name }}"
    dest: "/etc/nginx/sites-enabled/{{ service_name }}"
    state: link
  notify:
  - restart nginx
