- hosts: "{{ env }}_app"
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
  gather_facts: false
  become: yes
  become_user: "{{ application_user }}"
  become_method: sudo

  # Note: Ansible's service module is pretty flaky. Not handling either start
  # or restart of Nginx, thus gross ugly sudo calls to service. Note that sudo
  # is required here despite become/become_user/become_method. Don't shoot me,
  # I'm just the messenger. Until Ansible sorts this out, we are burying
  # warnings on these shell calls b/c Ansible whines about using sudo

  tasks:
    - name: copy nginx config
      template:
        src="{{ nginx_template | default('templates/nginx.j2') }}"
        dest=/home/apps/nginx/{{ project_name }}
      notify:
      - restart nginx

    - name: make sure nginx server is running
      shell: sudo service nginx start
        warn=False

  handlers:
    - name: restart nginx
      shell: sudo service nginx restart
        warn=False
