- hosts: "{{ env }}_app {{ env }}_work"
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
    - "{{ vault_dir }}/{{ project_name }}/vault.{{ env }}.yml"
  gather_facts: false
  become: yes
  become_user: "{{ application_user }}"
  become_method: sudo

  # Deploy the environment deployment branch to remote hosts. This play does
  # not handle sync/update from development to deployment branches or push
  # to remote repository -- run local.repository.yml for that

  #version={{ env }}

  tasks:
    - name: clone/pull project repo
      git:
        repo={{ project_repo }}
        dest={{ deploy_dir }}
        accept_hostkey=yes
        version={{ env }}
        key_file={{ git_key_file if git_key_file is defined else None }}
