- hosts: "{{ env }}_app"
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
    - "{{ vault_dir }}/{{ project_name }}/vault.{{ env }}.yml"
  gather_facts: false
  become: yes
  become_user: "{{ application_user }}"
  become_method: sudo

  # Tasks should be run once all by the same host. Ansible's run_once
  # will delegate to the first relevant host. To be more specific, we may
  # need to use delegate_to

  # sync up static files from the deployment env to S3
  #
  # Requires the AWS cli configured for S3 sync on the remote host delegated
  # for these tasks

  tasks:

    - name: prepare static files
      run_once: static_service == "s3"
      when: static_prep is defined
      shell: "{{ static_prep }}"
      args:
        chdir: "{{ application_dir }}"

    - name: sync to s3
      when: static_dir is defined and static_dest is defined and static_service is defined and static_service == "s3"
      run_once: true
      shell: aws s3 sync --acl public-read {{ static_dir }} {{ static_dest }}

    - name: ensure self-hosting static directory
      when: static_dest is defined and static_service is not defined or static_service == ""
      file: path={{ static_dest }} state=directory recurse=true

    - name: sync to self-hosting
      when: static_dir is defined and static_dest is defined and static_service is not defined or static_service == ""
      shell: cp -r {{ static_dir }} {{ static_dest }}
