- hosts: "{{ env }}"
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
  gather_facts: false
  become: yes

  tasks:
    - name: symlink nginx config
      file:
        src: "{{ nginx_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ project_name }}"
        state: link 
      notify:
      - restart nginx

  handlers:
    - name: restart nginx
      shell: systemctl restart nginx
        warn=False
