- hosts: 127.0.0.1
  connection: local
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
    - "{{ vault_dir }}/{{ project_name }}/vault.{{ env }}.yml"
  gather_facts: false

  tasks:

    # warn False on these tasks b/c we are calling git directly. Be on the
    # lookout for updates to the git module that will allow us to replace
    # some of these shell calls

    - name: get current working branch
      shell: git rev-parse --abbrev-ref HEAD
      args:
        chdir: "{{ project_root }}"
        warn: False
      register: original_branch

    #- name: "checkout development branch: {{ merge_from }}"
    #  shell: git checkout {{ merge_from }}
    #  args:
    #    chdir: "{{ project_root }}"
    #    warn: False

    # Don't use the git module here - it will overwrite local commits.
    # See: https://github.com/ansible/ansible-modules-core/issues/614
    #- name: "sync local development branch: {{ merge_from }}"
    #  shell: git pull; git push
    #  args:
    #    chdir: "{{ project_root }}"
    #    warn: False

    - name: "checkout deployment branch: {{ env }}"
      shell: git checkout {{ env }}
      args:
        chdir: "{{ project_root }}"
        warn: False

    #- name: "merge and sync deployment branch: {{ env }}"
    #  shell: git pull; git merge {{ merge_from }}; git push
    #  args:
    #    chdir: "{{ project_root }}"
    #    warn: False

    - name: "checkout original branch: {{ original_branch.stdout }}"
      shell: git checkout {{ original_branch.stdout }}
      args:
        chdir: "{{ project_root }}"
        warn: False

