- name: create env file
  template:
    src=templates/dotenv.j2
    dest="{{ env_file }}"

- name: create envrc file
  template:
    src=templates/envrc.j2
    dest="{{ envrc_file }}"
  notify:
    - allow envrc
    - restart service
