- name: create env file
  template:
    src=templates/dotenv.j2
    dest="{{ deploy_dir }}/.env"

- name: create envrc file
  template:
    src=templates/envrc.j2
    dest="{{ deploy_dir }}/.envrc"
  notify:
    - allow envrc
    - restart service
