- name: Run database migrations
  environment: "{{ init_env }}"
  community.general.django_manage:
    command: migrate
    project_path: "{{ deploy_dir }}"
    virtualenv: "{{ virtualenv }}"
  notify:
  - restart application
